### ISSUE TITLE
Use imported_files for imported files cleanup instead of recursive filesystem read

### ISSUE THREAD

**Issue by Suika** [thatfuckingbird/hydownloader#10]
https://github.com/thatfuckingbird/hydownloader/blob/master/hydownloader/importer.py#L117-L142

You have 10M files, 100k are imported. As it is now, it will have to query the whole FS and itearte over 10M files, just to delete 100k files _that are already recorded in the database_.
Do use the database for working on the cleanup jobs or whetever. When the files are deleted from the disk, the entry can also be deleted from the db.

**Comment by thatfuckingbird** [comment]
No, this is working as intended. On the next run, you would have 10M files in your db and it would have to check for the existence of 10M files on the fs, which would be much slower. Entries should not be deleted from the db, because (1) the point of the db is to keep track of what's imported (2) the metadata is also stored there which makes it possible to later extract more metadata and add it to Hydrus. For example, when notes are added to the API, the stored metadata can be used to retroactively add notes for files in Hydrus that were already deleted from the hydownloader data folder.

**Comment by thatfuckingbird** [comment]
Also, fixing #11 will speed this up, so this really won't be a problem.

**Comment by Suika** [comment]
I call bullshit:
```
  --no-include-metadata         Do not include metadata files in the action.
                                [default: False]

```
