### ISSUE TITLE
Newgrounds URLs are incorrect/broken

### ISSUE THREAD

**Issue by ponchojohn1234** [thatfuckingbird/hydownloader#25]
Newgrounds no longer uses ` https://www.newgrounds.com/portal/view/` for artwork, so the resulting URLs after appending `"index"` results in either a broken link or a link to a different submission.

**Comment by thatfuckingbird** [comment]
Do you have a suggestion on how to update that rule? Or alternatively, if you can send a current artwork metadata json so I have something to look at that would help too. I tried just now, but currently I'm getting blocked with an 503 error on all artworks for some reason...

**Comment by ponchojohn1234** [comment]
[newgrounds_2033408_Duality - Micha Jawkan.png.txt](https://github.com/thatfuckingbird/hydownloader/files/8748775/newgrounds_2033408_Duality.-.Micha.Jawkan.png.txt)
for this submission https://www.newgrounds.com/art/view/yuuyatails/duality-micha-jawkan

it seems to be using the end of the filename to form the url, but it's pretty unrealiable and some submissions have different characters that would break the url if it's used

**Comment by ponchojohn1234** [comment]
> it seems to be using the end of the filename to form the url, but it's pretty unrealiable and some submissions have different characters that would break the url if it's used
>
[newgrounds_1012914_02_fuhkirth,.yse_.jpg.txt](https://github.com/thatfuckingbird/hydownloader/files/8748789/newgrounds_1012914_02_fuhkirth.yse_.jpg.txt)
in this [example](https://www.newgrounds.com/art/view/nisetanaka/fuhkirth-yse) all the pictures aside from the main one have completely different filenames, so it would need to be taken from the main image metadata

**Comment by ponchojohn1234** [comment]
also since it's just using the title of the image i guess it would be possible to replace spaces and non-letter characters with regex or something from `""` since that value is the same on every image, not sure about the reliability tho

**Comment by thatfuckingbird** [comment]
Recovering URL form title sounds like a pain and probably there are other edge cases that make it even harder (too long titles might get truncated, etc.), but in your latter example I see a post_url field that looks like just what we want (not sure when exactly this is available since in the first txt it's missing...).
Currently I'm thinking about removing the broken rule and just adding one for the post_url, like this:
![image](https://user-images.githubusercontent.com/67429906/169713453-b761fcff-de8a-4357-a364-19946cf987a2.png)

Would this be better?
Now that I think about it, could it be that this post_url appeared after NG switched the URL format? So posts where there is no post_url field could use the old rule and if there is a post_url field then the new one instead. But just speculating here as I don't have much downloaded from the site.

**Comment by ponchojohn1234** [comment]
`"post_url"` appears for secondary images (i.e. all the ones after the first one, telltale sign being that the cursor doesn't change while hovering and can't be zoomed into)

**Comment by ponchojohn1234** [comment]
actually it seems that the metadata of the file has in fact changed, possibly at the same time that the url of the post changed

[newgrounds_1012914_fuhkirth,.yse？.png.txt](https://github.com/thatfuckingbird/hydownloader/files/8750341/newgrounds_1012914_fuhkirth.yse.png.txt)
[newgrounds_1012914_fuhkirth_.yse.png.txt](https://github.com/thatfuckingbird/hydownloader/files/8750342/newgrounds_1012914_fuhkirth_.yse.png.txt)

both if these json files are from the same post, the 2nd one is older (look at number of favorites)

**Comment by thatfuckingbird** [comment]
Looking at the older metadata file, the old URL format with the index doesn't work for that post, so I think there is no point in leaving the old rule even if there is no post_url, since it might still generate broken URLs anyway. Overall I think the best we can do is the new post_url rule in my previous post.
